# PostgreSQL for local dev
spring.datasource.url=jdbc:postgresql://localhost:5432/fixitdb_dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:fixit}
spring.datasource.password=${DB_PASSWORD:fixit}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak (local Docker)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/fixit
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/fixit/protocol/openid-connect/certs

# Liquibase debug
logging.level.liquibase=DEBUG
