spring.application.name=FixIt

# PostgreSQL (production)
spring.datasource.url=jdbc:postgresql://localhost:5432/fixitdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:fixit}
spring.datasource.password=${DB_PASSWORD:fixit}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
